### ISSUE TITLE
Enable SPM support and add Privacy Manifest

### ISSUE THREAD

**Issue by thanospapazoglou** [Worldline-Global-Collect/connect-sdk-client-swift#1]
Hey,

Currently, the SDK does not support integration via Swift Package Manager (SPM), which limits the ways we can include it in our projects. Additionally, it lacks a privacy manifest, which is essential for compliance with Apple’s privacy guidelines and to provide transparency to developers integrating the SDK.

Do you plan to release both of these in the near future?

Thanks

**Comment by WorldlineSolutionsIO** [comment]
Hello,

Thank you for your feedback!
We have added support for SPM and a Privacy Manifest file in our latest release. Please upgrade to version 6.1.0 of this SDK to use these features.

Kind regards
